# Generated by Django 5.1.5 on 2025-01-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_curriculum_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formacao',
            options={'verbose_name_plural': 'Formacoes'},
        ),
    ]
