version: '3'

services:
  backend:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    networks:
      - app-network

  frontend:
    build:
      context: ./web
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
