services:
  backend:
    build:
      context: ./server
    volumes:
      - ./server:/app
      - ./server/static:/app/static
      - ./server/staticfiles:/app/staticfiles
      - ./server/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    depends_on:
      - backend
    command: sh -c "npm ci && npm start"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
