version: '3'

services:
  backend:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    networks:
      - app-network

  frontend:
    build:
      context: ./web
    volumes:
      - ./web:/app
      - /app/node_modules # Evita conflitos de node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100 # Ajusta o intervalo de polling para arquivos
    depends_on:
      - backend
    command: sh -c "npm install && npm start" # Garante instalação antes do start
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
